language: php
addons:
  chrome: stable
.steps:
  - &lint_style |
      echo "------------------------"
      echo "Checking for PHP styling (PSR2) issues"
      composer global require "squizlabs/php_codesniffer=3.*"
      $HOME/.config/composer/vendor/bin/phpcs -p -n --extensions=php,inc --report-width=120 --standard=ci/phpcs.xml --report=full .
  - &lint_syntax |
      echo "------------------------"
      echo "Checking for PHP syntax errors"
      failSyntax=false;
      if find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"; then failSyntax=true; fi;
      if find . -type f -name "*.inc" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"; then failSyntax=true; fi;
      if $failSyntax; then
          exit 1;
      fi
  - &build_test |
      echo "------------------------"
      echo "Checking build and tests"
      echo "------------------------"
      echo "Build openemr via flex docker"
      cd ci
      docker-compose up
      cd ../
      echo "------------------------"
      echo "Install/configure active openemr instance"
      chmod 666 sites/default/sqlconf.php
      sudo chown -R www-data:www-data sites/default/documents
      sed -e 's@^exit;@ @' < contrib/util/installScripts/InstallerAuto.php > contrib/util/installScripts/InstallerAutoTemp.php
      php -f contrib/util/installScripts/InstallerAutoTemp.php rootpass=root loginhost=openemr server=mysql
      rm -f contrib/util/installScripts/InstallerAutoTemp.php
      echo "------------------------"
      echo "Turn on the api to allow api testing"
      mysql -u openemr --password="openemr" -h localhost -e "UPDATE globals SET gl_value = 1 WHERE gl_name = 'rest_api'" openemr
      echo "------------------------"
      echo "Prepare for testing"
      composer require --dev "phpunit/phpunit=8.*"
      composer require --dev "symfony/panther=^0.6"
      composer dump-autoload -o
      echo "------------------------"
      echo "Run all tests (testsuite openemr: unit, e2e, api)"
      php vendor/bin/phpunit --testsuite openemr --testdox
      echo "------------------------"
      echo "Run only unit tests"
      php vendor/bin/phpunit --testsuite unit --testdox
      echo "------------------------"
      echo "Run only e2e tests"
      php vendor/bin/phpunit --testsuite e2e --testdox
      echo "------------------------"
      echo "Run only api tests"
      php vendor/bin/phpunit --testsuite api --testdox
before_install:
  - echo "extension=ldap.so" >>php --ini | grep "Loaded Configuration" | sed -e "s|.:\s||"``
before_script:
  - echo 'error_reporting = "E_ALL & ~E_NOTICE & ~E_STRICT"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
jobs:
  include:
    - env: CI_JOB=lint_style
      php: '7.4'
      script: *lint_style
    - env: CI_JOB=lint_syntax
      php: '7.2'
      script: *lint_syntax
    - env: CI_JOB=lint_syntax
      php: '7.3'
      script: *lint_syntax
    - env: CI_JOB=lint_syntax
      php: '7.4'
      script: *lint_syntax
    - env: CI_JOB=build_test
      php: '7.2'
      script: *build_test
    - env: CI_JOB=build_test
      php: '7.3'
      script: *build_test
    - env: CI_JOB=build_test
      php: '7.4'
      script: *build_test
