# Use admin/pass as user/password credentials
version: '3.1'
services:
  mysql:
    restart: always
    image: mysql
    command: ['mysqld','--character-set-server=utf8']
    environment:
      MYSQL_ROOT_PASSWORD: !rt&5YU
    ports:
    - 3307:3306
  openemr:
    restart: always
    container_name: openemr_local_development 
    build: ./contrib/util/docker
    ports:
    - 8080:80
    - 8081:443
    volumes:
    - .:/var/www/localhost/htdocs/openemr
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: !rt&5YU
      MYSQL_USER: derek
      MYSQL_PASS: Qa@er5
      OE_USER: admin
      OE_PASS: 3de$EDC
    links:
    - mysql