services:
  openemr:
    image: openemr/openemr:7.0.2
    ports:
      - 80:80
      - 443:443
    environment:
      MYSQL_HOST: 18.217.152.197
      MYSQL_USER: root
      MYSQL_PASS: password
      MYSQL_DATABASE: openemr
      OE_USER: admin
      OE_PASS: pass

# services:
#   openemr:
#     image: openemr/openemr:7.0.2
#     ports:
#       - 80:80
#       - 443:443
#     environment:
#       MYSQL_HOST: localhost
#       MYSQL_USER: openemr
#       MYSQL_PASS: openemr
#       MYSQL_DATABASE: openemr
#       OE_USER: admin
#       OE_PASS: pass
#   mysql:
#     image: mariadb:10.6
#     container_name: openemr-mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpass   # Root password for MySQL
#       MYSQL_DATABASE: openemr         # Database name
#       MYSQL_USER: openemr             # Database user
#       MYSQL_PASSWORD: openemr         # Password for the database user
#     ports:
#       - 3306:3306
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data: