# Use admin/pass as user/password credentials to login to openemr (from OE_USER and OE_PASS below)
# MYSQL_HOST and MYSQL_ROOT_PASS are required for openemr
# MYSQL_USER, MYSQL_PASS, OE_USER, MYSQL_PASS are optional for openemr and
#   if not provided, then default to openemr, openemr, admin, and pass respectively.
#
# NOTE need to change command from mysqld to mariadbd when update to mariadb 11.4

services:
  openemr:
    image: openemr/openemr:7.0.2
    ports:
      - 80:80
      - 443:443
    environment:
      MYSQL_HOST: medicalinktest.clo8kiei8wzd.us-east-2.rds.amazonaws.com
      MYSQL_USER: admin
      MYSQL_PASS: Admin123
      MYSQL_DATABASE: medicalinktest
      OE_USER: admin
      OE_PASS: pass
