services:
  openemr:
    image: openemr/openemr:7.0.2
    ports:
      - 80:80
      - 443:443
    environment:
      MYSQL_HOST: medicalink-instance-1.clo8kiei8wzd.us-east-2.rds.amazonaws.com
      MYSQL_USER: root
      MYSQL_PASS: password
      MYSQL_DATABASE: openemr
      OE_USER: admin
      OE_PASS: pass

# services:
#   openemr:
#     image: openemr/openemr:7.0.2
#     ports:
#       - 80:80
#       - 443:443
#     environment:
#       MYSQL_HOST: localhost
#       MYSQL_USER: openemr
#       MYSQL_PASS: openemr
#       MYSQL_DATABASE: openemr
#       OE_USER: admin
#       OE_PASS: pass
#   mysql:
#     image: mariadb:10.6
#     container_name: openemr-mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpass   # Root password for MySQL
#       MYSQL_DATABASE: openemr         # Database name
#       MYSQL_USER: openemr             # Database user
#       MYSQL_PASSWORD: openemr         # Password for the database user
#     ports:
#       - 3306:3306
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:

phpmyadmin:
    restart: always
    image: phpmyadmin
    ports:
    - 8310:80
    environment:
      PMA_HOSTS: mysql
  couchdb:
    restart: always
    image: couchdb
    ports:
    - 5984:5984
    - 6984:6984
    volumes:
    - ../library/couchdb-config-ssl-cert-keys/local.ini:/opt/couchdb/etc/local.ini:rw
    - ../library/couchdb-config-ssl-cert-keys/easy/ca.pem:/etc/ssl/ca.pem:ro
    - ../library/couchdb-config-ssl-cert-keys/easy/server-cert.pem:/etc/ssl/server-cert.pem:ro
    - ../library/couchdb-config-ssl-cert-keys/easy/server-key.pem:/etc/ssl/server-key.pem:ro
    - couchdbvolume:/opt/couchdb/data
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
  openldap:
    restart: always
    image: openemr/dev-ldap:easy
    environment:
      LDAP_TLS_VERIFY_CLIENT: try
      LDAP_TLS_CA_CRT_FILENAME: ca.pem
      LDAP_TLS_CRT_FILENAME: server-cert.pem
      LDAP_TLS_KEY_FILENAME: server-key.pem