# Use admin/pass as user/password credentials to login to openemr (from OE_USER and OE_PASS below)
# MYSQL_HOST and MYSQL_ROOT_PASS are required for openemr
# MYSQL_USER, MYSQL_PASS, OE_USER, MYSQL_PASS are optional for openemr and
#   if not provided, then default to openemr, openemr, admin, and pass respectively.
# NOTE need to change command from mysqld to mariadbd when update to mariadb 11.4

services:
  openemr:
    image: openemr/openemr:7.0.2
    ports:
      - 80:80
      - 443:443
    environment:
      MYSQL_HOST: 3.145.57.95
      MYSQL_USER: admin
      MYSQL_PASS: password
      MYSQL_DATABASE: medicalinkdb
      OE_USER: admin
      OE_PASS: pass

# services:
#   openemr:
#     image: openemr/openemr:7.0.2
#     ports:
#       - 80:80
#       - 443:443
#     environment:
#       MYSQL_HOST: localhost
#       MYSQL_USER: openemr
#       MYSQL_PASS: openemr
#       MYSQL_DATABASE: openemr
#       OE_USER: admin
#       OE_PASS: pass
#   mysql:
#     image: mariadb:10.6
#     container_name: openemr-mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpass   # Root password for MySQL
#       MYSQL_DATABASE: openemr         # Database name
#       MYSQL_USER: openemr             # Database user
#       MYSQL_PASSWORD: openemr         # Password for the database user
#     ports:
#       - 3306:3306
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:

